### ISSUE TITLE
No way to disable Jumping

### ISSUE THREAD

**Issue by pinipy** [HyChrod/Friends#1]
The jumping feature is unnecessary for my server, but there is no permission node to disable said feature. I can disable it through the GUI but players can still manually type the command.

**Comment by HyChrod** [comment]
I will add an option to fully disable jumping in the next update

**Comment by HyChrod** [comment]
# Fixed

**Comment by pinipy** [comment]
Uh, your latest update overwrote the configs??
Which isn't the biggest issue aside for the fact that it enabled the player head again when I  had it set to disabled. Which means it just voided anything in my player's 4th slot??

**Comment by HyChrod** [comment]
It should not have done that. I am sorry.
