### ISSUE TITLE
Command usage inside of GUI

### ISSUE THREAD

**Issue by ShadowChildUK** [HyChrod/Friends#2]
Hello.

I have created a GUI with a plugin called DeluxeHub to launch the friends GUI on click of an item. However, for some reason, it's not working. It's executing the command `/friends`, it says the command is not found. I have the `OpenGUIWithCommand` set to true. `/party` works fine, it's just the friends.

**Comment by HyChrod** [comment]
Use /friendsgui it's a command especially build for this purpose
