### ISSUE TITLE
[Bug] MySQL Timeout

### ISSUE THREAD

**Issue by evanthebearge** [HyChrod/Friends#4]
Hi,

I am having this issue with the Friends plugin on Waterfall Bungeecord. I tried changing my MySQL connection properties to see if it would fix, but it is still persisting.

Error Message: https://hastebin.com/jijayalaru.shell - Looks like it is timing out.

MySQL.YML: https://hastebin.com/unimobuseb.bash - I added the arguments Auto Reconnect and Timezone to see if it would fix, but it had no effect.

I think it might be a possible issue with the databases my host has supplied, as I have had previous issues with them. The Bungeecord server and MySQL server are hosted in the same region.

If this issue is not in relation with the plugin, but indeed my host, please let me know, Thanks.

**Comment by HyChrod** [comment]
I will have a look at it

**Comment by HyChrod** [comment]
Should be fixed in Version 1.3.2 and following.
If not, please post again

- Flo
