### ISSUE TITLE
[Help] Not allowed to perform this command

### ISSUE THREAD

**Issue by RisedSky** [HyChrod/Friends#5]
I can't do the command even i'm OP
is this intended ?
is this a bug ?
i tested without any perm plugin doesn't work
tried too with luckperms doesn't work too
version 1.15.2
bungee mysql + lobby mysql
![image](https://user-images.githubusercontent.com/23197999/86850577-cbd99480-c0b1-11ea-88f2-8fbb5dd2c363.png)

**Comment by RisedSky** [comment]
Using waterfall-360 and paper-375
same with /party invite

**Comment by HyChrod** [comment]
When using BungeeMode, you have to give the permissions on BungeeCord. You need a permissions plugin for BungeeCord to manage this

**Comment by RisedSky** [comment]
Oh..
You should add this notice in your config file or somewhere
also, it is cool you help me :) !
i'm using luckpermsbungee so
thank you, i close this "issue"
