### ISSUE TITLE
Restarting the server doesnt save last online date

### ISSUE THREAD

**Issue by Welcome234** [HyChrod/Friends#7]
Everytime I restart my server the last online clears and It says 1970, The Friend add date works.

**Comment by HyChrod** [comment]
Bungee? Single-Server? MySQL?

Please provide some more information about how you are using Friends

**Comment by Welcome234** [comment]
Single-Server

**Comment by HyChrod** [comment]
I will have a look at it

**Comment by HyChrod** [comment]
#Fixed in v1.3.3
