### ISSUE TITLE
SSL error when connecting to MySQL

### ISSUE THREAD

**Issue by Equity7** [HyChrod/Friends#8]
Hi. I am running 1.16.1 Paper on a bungee network and the latest version of Friends and I have the one plugin (only Friends) on the server to test this error. I actually have Friends plugin on 5 servers and I am getting this error on all of them. I have even tried 2 different MySQL db's to make sure it wasn't the db. I didn't change the plugin's folder at all from the default except for the MySQL file. I must be doing something wrong and I want to keep this on my servers so please advise! This error spams dozens of times.

1.07 09:50:21 [Server] INFO Enabling FriendsRELOADED v1.3.2
21.07 09:50:21 [Server] INFO HikariPool-1 - Started.
21.07 09:50:22 [Server] WARN Tue Jul 21 09:50:22 EDT 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
21.07 09:50:22 [Server] WARN Tue Jul 21 09:50:22 EDT 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
21.07 09:50:22 [Server] WARN Tue Jul 21 09:50:22 EDT 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
21.07 09:50:23 [Server] WARN Tue Jul 21 09:50:23 EDT 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
21.07 09:50:23 [Server] WARN Tue Jul 21 09:50:23 EDT 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
21.07 09:50:23 [Server] WARN Tue Jul 21 09:50:23 EDT 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
21.07 09:50:23 [Server] WARN Tue Jul 21 09:50:23 EDT 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
21.07 09:50:23 [Server] WARN Tue Jul 21 09:50:23 EDT 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
21.07 09:50:23 [Server] WARN Tue Jul 21 09:50:23 EDT 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
21.07 09:50:23 [Server] WARN Tue Jul 21 09:50:23 EDT 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
21.07 09:50:23 [Server] WARN Tue Jul 21 09:50:23 EDT 2020 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
21.07 09:50:24 [Server] INFO Friends | Connected to MySQL!
21.07 09:50:24 [Server] INFO Friends | Plugin was successfully loaded!
21.07 09:50:24 [Server] INFO Party | The plugin was successfully loaded!

**Comment by HyChrod** [comment]
I already know about that. Will be fixed in the next version. 
Sadly you have to live with this warning until then

**Comment by Equity7** [comment]
Oh that's great news! No problem I can wait!

**Comment by HyChrod** [comment]
#Fixed in v1.3.3
